### PR TITLE
Update JMH to 1.17.1

### PR DESCRIPTION
**Pull request by golem131**

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks a lot, I'll release right away

**Comment by ktoso** [comment]
I've released `0.2.18 ` which includes this upgrade, happy hakking

**Comment by slandelle** [comment]
@ktoso Did you miss something?

> sbt.ResolveException: unresolved dependency: pl.project13.scala#sbt-jmh-extras;0.2.18: not found

**Comment by ktoso** [comment]
I didn't, but it takes time for the artifact to appear on maven central - it'll be there in an hour or two.

**Comment by slandelle** [comment]
Ah, ok, I thought it was part of the plugin, so I expected it to be on Bintray, hence instantly.
Thanks!

**Comment by ktoso** [comment]
Yeah - sorry, the sbt plugin goes to bintray as that's the right place for it, but the extras lib goes to maven central via sonatype :~

**Comment by slandelle** [comment]
Yeah, get it now :) Usually, sync takes ~30min, except when it's broken...

**Pull request merged**
