### PR TITLE
add import in Readme

### PR DESCRIPTION
**Pull request by julien-truffaut**

### CODE REVIEW

**Comment by ktoso** [comment]
Technically this is not needed, see: https://github.com/ktoso/sbt-jmh/blob/master/sbt-jmh-tester/build.sbt#L1 "just works", because of how auto plugins work.

Did you encounter an actual problem and needed to use the import explicitly?

**Comment by julien-truffaut** [comment]
yes sbt compile failed until I add this import. Does it work for you without import?

**Comment by ktoso** [comment]
Like I pointed out https://github.com/ktoso/sbt-jmh/blob/master/sbt-jmh-tester/build.sbt#L1 this works, I use if pretty often.

What's your setup? sbt version, project files?

**Comment by julien-truffaut** [comment]
sbt 0.13.8
multiple sub projects, only one sub project with jmh dependency

I will try again at home with a personal project to see if the import is really required or not.

**Comment by ktoso** [comment]
I think it may be related to the multiple projects setup, and where exactly you include the plugin. Could you explain that part of your setup?

**Comment by julien-truffaut** [comment]
basically I have a module like this define in a Build.scala

```scala
lazy val bench: Project = Project(
    id    = "bench",
    base  = file("bench"),
    dependencies = Seq(moduleA), // some module I want to benchmark
    settings = projectSettings // common setting in my project
  ).enablePlugins(JmhPlugin)
```

**Comment by ktoso** [comment]
Well, so if you're using `Build.scala` you will have to do the imports.
The instructions are for `build.sbt` files, which does the imports "automagically".

**Comment by julien-truffaut** [comment]
ah my bad, I didn't know that build.scala and build.sbt had different behavior regarding plugin...

I will update the PR as you suggested.

**Comment by ktoso** [comment]
No problem, glad we got to the bottom of this :-)
Thanks in advance for the updated PR!

**Comment by julien-truffaut** [comment]
is it ok?

**Comment by ktoso** [comment]
Great, thanks

**Pull request merged**
