### PR TITLE
Add docs for classDirectory+dependencyClasspath config

### PR DESCRIPTION
**Pull request by magro**
Here's a proposal, I hope location and content is ok, otherwise feel free to move/change etc. :-)

Refs #73

### CODE REVIEW

**Comment by ktoso** [comment]
Looks good. It's the right place as well. 
Thanks a lot @magro !

**Comment by magro** [comment]
Great :-) What do you think when you'll push the next release?

**Comment by ktoso** [comment]
Now. (-:

**Comment by magro** [comment]
Yeah, super awesome! :-)

**Comment by ktoso** [comment]
Published 0.2.8, should be available any seconds now.
Thanks for your help!


On 6 July 2016 at 00:13:30, Martin Grotzke (notifications@github.com) wrote:

Yeah, super awesome! :-)

**Comment by magro** [comment]
Many thanks back!

**Pull request merged**
