### PR TITLE
Upgrade to JMH 1.16 and Scala 2.12.0

### PR DESCRIPTION
**Pull request by paplorinc**
FIxes https://github.com/ktoso/sbt-jmh/issues/90

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks a lot, I can release right away actually - let's have travis validate it,

**Comment by ktoso** [comment]
Hmm so this problem still exists:

```
[error] Illegal type for the return type of public method in @AuxCounters.
[error]    [org.openjdk.jmh.generators.reflection.RFMethodInfo@3ff049d9]
```

**Comment by paplorinc** [comment]
Wanted to upgrade to `1.16`, not `1.15`, sorry.

**Comment by paplorinc** [comment]
@ktoso, passed :)

**Comment by ktoso** [comment]
Excellent :)
Thanks!

I'll cut a release.

**Comment by ktoso** [comment]
Done!
extras may take a while until it shows up on maven central

**Comment by paplorinc** [comment]
It's working, thanks :)

**Pull request merged**
