### PR TITLE
Update dep on JMH in JmhPlugin to 1.11

### LINKED ISSUE #60: Plugin version 2.4 depends on wrong version of JMH
According to

https://github.com/ktoso/sbt-jmh/blob/185131ce460f864e8e5e1344c895e8fccfd41338/build.sbt#L17

the plugin is built against JMH 1.11. However, according to

https://github.com/ktoso/sbt-jmh/blob/c49d49b564eb2d2dbbb2be3c41ac2197b977f574/src/main/scala/pl/project13/scala/sbt/JmhPlugin.scala#L32

the plugin adds JMH 1.10.3 to the plugged-in project's library dependencies.

### PR DESCRIPTION
**Pull request by mallman**
Fixes #60

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks for the PR!
I think it'll be hard to get more more dry than 1 line per version of: project, jmh :)

**Comment by ktoso** [comment]
I'll release it in a bit today

**Comment by mallman** [comment]
I was referring to the duplication of JMH version numbers in build.sbt and JmhPlugin.scala. I'm presuming those versions should be the same, no?

**Comment by ktoso** [comment]
Ah yes, that's correct should be fixed, I'll  open a ticket.

**Pull request merged**
