### PR TITLE
Support async-profiler, improve JFR profiler

### PR DESCRIPTION
**Pull request by retronym**
Existing Flight Recorder profiler modified to:

  - Discard samples collected during the warmup period
  - By default, use AsyncGetCallTrace based sampling
  - Make `stackdepth` configurable and increase the default
  - Optionally, generate flamegraphs for (requires local clone of
    [brendangregg/FlameGraph](https://github.com/brendangregg/FlameGraph) and a local clone and build of
    [chrishantha/jfr-flame-graph](https://github.com/chrishantha/jfr-flame-graph).)

Support async-profiler:
  - Requires local clone and build of [jvm-profiling-tools/async-profiler](https://github.com/jvm-profiling-tools/async-profiler)
  - Samples only collected after warmup has completed
  - CPU and HEAP events supported.
  - Optionally, generate flame graphs

async-profiler is primarily Linux based, but it also has preliminary support for MacOS.

The location of the external tools can be provided with the followng environment
variables: `FLAME_GRAPH_DIR`, `JFR_FLAME_GRAPH_DIR`, `ASYNC_PROFILER_DIR`. Alternatively,
these can be provided as options to the profiler.

Help:

```
sbt> jmh:run Bench -prof jmh.extras.JFR:help
Option                              Description
------                              -----------
--debugNonSafepoints <Boolean>      (default: [true, false])
--dir <Output directory>
--events <JfrEventType>             (default: [CPU, ALLOCATION_TLAB,
                                      ALLOCATION_OUTSIDE_TLAB, EXCEPTIONS,
                                      LOCKS])
--flameGraphDir <directory>       Location of clone of https://github.
                                      com/brendangregg/FlameGraph. Also
                                      can be provided as $FLAME_GRAPH_DIR
--flameGraphDirection <Directions>  Directions to generate flamegraphs
--flameGraphOpts                    Options passed to FlameGraph.pl
--flightRecorderOpts
--help                              Display help.
--jfrFlameGraphDir <directory>    Location of clone of https://github.
                                      com/chrishantha/jfr-flame-graph.
                                      Also can be provided as
                                      $JFR_FLAME_GRAPH_DIR
--jfrFlameGraphOpts                 Options passed to flamegraph-output.sh
--stackDepth <Integer>              (default: 1024)
--verbose <Boolean>                 Output the sequence of commands
                                      (default: false)

```

```
sbt> jmh:run Bench -prof jmh.extras.Async:help

Option                              Description
------                              -----------
--asyncProfilerDir <directory>    Location of clone of https://github.
                                      com/jvm-profiling-tools/async-
                                      profiler. Also can be provided as
                                      $ASYNC_PROFILER_DIR
--dir <<directory>>                 Output directory
--event <AsyncProfilerEventType>    Event to sample (default: [CPU, HEAP])
--flameGraphDir <directory>       Location of clone of https://github.
                                      com/brendangregg/FlameGraph. Also
                                      can be provided as $FLAME_GRAPH_DIR
--flameGraphDirection <Directions>  Directions to generate flamegraphs
                                      (default: [BOTH, NONE, FORWARD,
                                      REVERSE])
--flameGraphOpts                    Options passed to FlameGraph.pl
--framebuf <Long>                   Size of profiler framebuffer (default:
                                      8388608)
--help                              Display help.
--threads <Boolean>                 profile threads separately (default:
                                      [false, true])
--verbose <Boolean>                 Output the sequence of commands
                                      (default: false)

```

Examples:

```
sbt> jmh:run Bench -f1 -wi 5 -i5 -prof jmh.extras.Async:event=HEAP;dir=/tmp/profile-async;flameGraphOpts=--minwidth,2;asyncProfilerDir=/code/async-profiler;flameGraphDir=/code/FlameGraph

sbt> jmh:run Bench -f1 -wi 5 -i5 -prof jmh.extras.JFR:dir=/tmp/profile-jfr;flameGraphDir=/code/FlameGraph;jfrFlameGraphDir=/code/jfr-flame-graph;flameGraphOpts=--minwidth,2;verbose=true
```

### CODE REVIEW

**Comment by retronym** [comment]
Ready for review now.

**Comment by retronym** [comment]
Generated results for linux and Mac:

https://www.dropbox.com/sh/2hx11izg98wgdhu/AAAkK0FFSTCYk3fs4vrxWLCOa?dl=0

**Comment by ktoso** [comment]
Lookin great!

**Comment by ktoso** [comment]
Did not have time yet to verify manually, but I trust your work on this! :-)
I'll release a version so people can try it out then!

**Comment by retronym** [comment]
Blog: http://kto.so/2017/12/10/automatic-flamegraph-generation-from-jmh-benchmarks-using-sbt-jmh-extras-plain-java-too/

**Pull request merged**
